### ISSUE TITLE
Modulo Pagos y Razon Social

### ISSUE THREAD

**Issue by lugalindo8** [ISWPOLI/Monotributo#106]
- [x] - Realizar Crud de la entidad Pagos y la entidad Razon Social.
- [x] - Crear cada uno de sus respectivos métodos en Postman  cumpliendo con el orden correspondiente al modulo realizado.
- [x] - Documentar y/o describir la funcionalidad de cada metodo haciendo uso de las herramientas proporcionadas por Postman.
- [x] - Realizar pruebas de los metodos realizados, subir los cambios al repositorio en Git Hub y sicronizar el proyecto en Postman.

**Comment by andahefa** [comment]
Se realizan las actividades y se suben los cambios a github.
