### ISSUE TITLE
Prototipos "Monotributo"

### ISSUE THREAD

**Issue by lagaribello** [ISWPOLI/Monotributo#43]
**Tareas**

- [x] Reunión de contextualización de los prototipos diseñado con cada líder de los sub-grupos creados

- [x] Aporte al diseño de los prototipos por parte de cada sub-grupo

- [x] Corrección de prototipos de aplicativo "Monotributo"

**Comment by nataliaObando** [comment]
Se cierra historia con sus tareas completadas
